### PR TITLE
added GA html tag

### PR DESCRIPTION
**Pull request by TrevorOctober**

### CODE REVIEW

**Comment by TrevorOctober** [comment]
@codiebeulaine Ready for review cc @miltontony

**Comment by codiebeulaine** [comment]
👍 once travis

**Comment by TrevorOctober** [comment]
@codiebeulaine Ready for re-review cc @miltontony

**Comment by codiebeulaine** [comment]
@TrevorOctober 👍 from me. @miltontony cake?

**Comment by miltontony** [comment]
🍰

**Pull request merged**
