### PR TITLE
Pick a random article that is descendant of a section

### PR DESCRIPTION
**Pull request by saeedmb8**

### CODE REVIEW

**Comment by saeedmb8** [comment]
@codiebeulaine ready for review

**Comment by codiebeulaine** [comment]
@saeedmb8 we need tests for pulling a descendant article as a random article

**Comment by saeedmb8** [comment]
@codiebeulaine fixed the test that was only checking for the children you also have a test for activating the content rotation on sub-sections

**Comment by codiebeulaine** [comment]
👍

**Pull request merged**
