### PR TITLE
Miscellaneous minor fixes to tidy up and improve Python 3 compatibility

### PR DESCRIPTION
**Pull request by alexmuller**
This might look like a lot but all the commits are small and self-contained :). I've put more details in the commit messages where needed.

### CODE REVIEW

**Comment by codiebeulaine** [comment]
Thanks for always making time for this @alexmuller

**Comment by nathanbegbie** [comment]
There's a `.iteritems()` that still needs squashing: https://github.com/praekelt/molo/pull/502/commits/a5d64f8c50f06df263db8f152429a8c611133bcc#diff-97195af90b0c894464325cbdbdac3d4fR723

**Comment by nathanbegbie** [comment]
and another `.iteritems()` here: . . . and here https://github.com/praekelt/molo/blob/minor-fixes-improve-codebase/molo/core/tasks.py#L443

**Comment by alexmuller** [comment]
Thanks, this one was just because I got a bit bored on the train :). Updated!

**Pull request merged**
