### PR TITLE
remove values method call from fake qs causing attr errors

### PR DESCRIPTION
**Pull request by moh-moola**
Remove values method call from fake queryset causing attribute errors

https://sentry.io/organizations/praekeltorg-gem/issues/1532850131/?project=161240&query=is%3Aunresolved

### CODE REVIEW

**Review by KaitCrawford — APPROVED** [review]
:+1: 
for my own understanding: why does `values_list` work fine when `values` doesn't?

**Comment by moh-moola** [comment]
@KaitCrawford Values does not return a flat list of values instead a key, val dict and values_list can be flexible

**Comment by KaitCrawford** [comment]
@moh-moola ah ok, so `values_list` doesn't throw an error if it comes across an object that doesn't have the attr? but `values` does?
It's odd that they'd make such similar methods behave so differently.

**Comment by moh-moola** [comment]
The query set passed to the template tags varies, it could be a Queryset or a FakeQueryset, and the FakeQueryset class does not implement the methods... there is a check for this in the case page previews are being served

**Pull request merged**
