### PR TITLE
Elasticsearch2 support

### PR DESCRIPTION
**Pull request by m1kola**
* 94f06ba - almost exact copy of the https://github.com/torchbox/wagtail/pull/2573 and related PRs into Wagtail's core.
* a34a72d - Fixes `search_fields` and removes `TagSearchable`
* 0f6180d - Makes search view compatible with elasticsearch back-ends. It will also works with DB backend. **You need to make same changes on sites which has been created from the template**.

You can use Elasticsearch 2 with the following settings
```python
WAGTAILSEARCH_BACKENDS = {
    'default': {
        'BACKEND': 'molo.core.wagtailsearch.backends.elasticsearch2',
        'INDEX': '%your_index_name%',
    },
}
```

When Wagtail 1.7 released, you can upgrade and simply replace import `molo.core.wagtailsearch.backends.elasticsearch2` with `wagtail.wagtailsearch.backends.elasticsearch2`. Then you will be able to remove `molo.core.wagtailsearch` module.

### CODE REVIEW

**Comment by m1kola** [comment]
I'll take a look at test on Monday.

**Comment by m1kola** [comment]
PR has been updated. I've added a couple of words to original description (see the first post).

I also excluded the temporary code (`molo.core.wagtailsearch`) from `flake8` check. It will be easier to make changes (including text highlighting), if our copy look similar to Wagtail 1.7 code.

**Comment by m1kola** [comment]
d1a51ec - as per discussion with @miltontony, this commit moves the search views into the `molo.core` module.

**Comment by miltontony** [comment]
👍 @m1kola thanks! 
I'm going to land this. Any additional changes can be in a separate PR.

**Comment by m1kola** [comment]
Thanks @miltontony.

I've created https://github.com/torchbox/wagtail/pull/3004 for highlighting support. I'll back-port these changes into molo (in a separate PR), when they accepted in Wagtail.

**Pull request merged**
