### PR TITLE
Update import UI to take site url as input

### LINKED ISSUE #123: Update import UI to take site url as input
At the moment, the user searches through a list of repo names, but #116 allows us to fetch repo names from a site url.

### PR DESCRIPTION
**Pull request by justinvdm**
Resolves #123 (needed to create a new PR, since I linked the wrong PR to #123).

### CODE REVIEW

**Comment by justinvdm** [comment]
@miltontony @saeedmb8 depends on #124, otherwise ready for review.

@peterp this PR contains react stuff, if you'd like to take a look (once #124 lands).

**Comment by justinvdm** [comment]
Ready for review.

**Comment by miltontony** [comment]
Is the UI able to handle `http://some-site-url.com/` - the test I see only shows `foo.com` as the payload

**Comment by justinvdm** [comment]
> Is the UI able to handle http://some-site-url.com/ - the test I see only shows foo.com as the payload

Yep, adding a test sounds like a good idea, will do.

**Comment by justinvdm** [comment]
@miltontony Ah, we actually do have a test for this [here](https://github.com/praekelt/molo/blob/develop/client/tests/views/git-importer/api.test.js#L176-L184).

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
