### PR TITLE
Use cookie cutter for a project template.

### PR DESCRIPTION
**Pull request by smn**

### CODE REVIEW

**Comment by smn** [comment]
@miltontony ready for review, to test this out do:

```sh
mkdir ~/test
cd ~/test
source $PATH_TO_MOLO_REPO/ve/bin/activate
molo scaffold foo
```

From then onwards follow the instructions in `foo/README.rst`

**Comment by miltontony** [comment]
@smn I'm not seeing the actual files (settings etc)

**Comment by smn** [comment]
2__sdehaan_smn____desktop_test_foo__zsh_

**Comment by miltontony** [comment]
I think we should move `manage.py` and the `project` folder to a `cookie_cutter` folder. That way this project remains a module only.

**Comment by smn** [comment]
@miltontony thanks for raising, still not sure what the issue was there but it's been fixed.

**Comment by miltontony** [comment]
:+1:

**Pull request merged**
