### PR TITLE
add published date to use for latest articles

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by smn** [comment]
:+1: but what is `first_published_at` now being used for?

**Comment by miltontony** [comment]
It's not being used for anything since we don't really care when an article was first published.

**Comment by miltontony** [comment]
Also, not ready to merge yet - there's an odd bug that it's not setting the `published_dated` when saved via the UI.

**Comment by miltontony** [comment]
no activity in a long time

**Pull request closed without merging**
