### PR TITLE
added new field for GA tag

### PR DESCRIPTION
**Pull request by TrevorOctober**

### CODE REVIEW

**Comment by TrevorOctober** [comment]
@codiebeulaine Ready for review cc @miltontony

**Comment by codiebeulaine** [comment]
@TrevorOctober 👍, but can you add a screenshot of the admin please

**Comment by TrevorOctober** [comment]
screen shot 2016-07-20 at 3 01 03 pm

**Comment by hodgestar** [comment]
:+1: from me.

I assume there will be a later PR that will actually use these?

**Comment by codiebeulaine** [comment]
@hodgestar yip :)

**Pull request merged**
