### PR TITLE
added new social media fields

### PR DESCRIPTION
**Pull request by TrevorOctober**

### CODE REVIEW

**Comment by TrevorOctober** [comment]
@saeedmb8 @miltontony Please review

**Comment by saeedmb8** [comment]
@TrevorOctober awesome :cake: first step is done, now you need to add migrations and then some tests for it.

**Comment by TrevorOctober** [comment]
@saeedmb8 @miltontony Ready for review

**Comment by saeedmb8** [comment]
:+1:

**Pull request merged**
