### PR TITLE
Molo 568: Results table page scroll

### PR DESCRIPTION
**Pull request by Mitso**

### CODE REVIEW

**Comment by Mitso** [comment]
@projectmushroom please review 

Issue:
The JS is not smooth, 

Decision 
Vertical and horizontal scroll is disabled when scrolled outside of table

wagtail-table

**Comment by projectmushroom** [comment]
@Mitso I see you've got the filter's on the left on Admin View, are you sure your browser isn't running a older cached stylesheet? I've got mine right aligned
screen shot 2017-11-06 at 14 50 09

**Comment by Mitso** [comment]
@projectmushroom the issue I have here is on smaller screen it's difficult navigate with the filter on the way. I'm interested to discuss why you choose to have it there?

**Comment by projectmushroom** [comment]
@Mitso cool NP, I didn't change anything, it's been on the right of my view the whole time, even with your branch checked out. I'm not seeing the left aligned filters at all

**Pull request merged**
