### PR TITLE
Documentation is unclear on how to go forward after `molo scaffold ...`

### PR DESCRIPTION
**Pull request by smn**
@bruskiza got stuck on trying to run tests for the molo repo, not the newly scaffolded project.

### CODE REVIEW

**Comment by smn** [comment]
@bruskiza please review

**Comment by bruskiza** [comment]
Getting there... when scaffolding the base app the new app doesn't have any tests.

I can now run the tests with the following output:

bru:myapp bruce$ ./manage.py test
Creating test database for alias 'default'...

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
Destroying test database for alias 'default'...
bru:myapp bruce$ 


Is it up to the user or the scaffolded app to write the new tests?

If it's the user, we can point them to how to write tests, if it's the scaffolded app, then the app should have at least an initial test surely?

**Comment by smn** [comment]
Considering a scaffolded application is largely empty I'm not entirely sure what tests to add.
I'll give it some thought.

**Comment by smn** [comment]
@bruskiza the commit you made now conflicts with the same change

**Comment by smn** [comment]
sorry hit enter too early:

@bruskiza the commit you made now conflicts with the same change made in #23. Generally what we do in these kinds of situations is merge in #23 into develop when reviewed, then merge develop in this feature branch to pull in the latest changes. That way you avoid the need to make the changes twice (and as a result, the conflict).

**Comment by smn** [comment]
@bruskiza I'm going to leave it without tests, our expectation is that developers should know about tests, it's standard Django stuff and Django's got good documentation on how to write tests.

**Comment by bruskiza** [comment]
No problem. Thanks.

**Comment by bruskiza** [comment]
:+1:

**Comment by smn** [comment]
http://molo.readthedocs.org/ done.

**Pull request merged**
